// changelog.js
// -----------------------------------------------------------------------------
// The in-game update log, newest first. Player-facing one-liners — no dev jargon.
// Opened from a button in Settings. Goes all the way back to the first build.
//
// When you ship a release, add a line at the TOP.

export const CHANGELOG = [
  { v: "2.91.0", note: "The loading screen now also plays on startup, arriving into the home screen." },
  { v: "2.90.0", note: "A loading screen before each run — a random wait with a rotating quick tip. (Entities can't jump!)" },
  { v: "2.89.0", note: "Spectated runs now show the other inhabitants moving and the player's own sonar pings, not just their path." },
  { v: "2.88.0", note: "Spectate leaderboard runs: click a daily entry to watch that run play back through its maze. Pauses are skipped." },
  { v: "2.87.1", note: "The death cutscene now lights the room, so you can actually see it." },
  { v: "2.87.0", note: "The death sequence is now one continuous shot: you collapse into a piece of meat where you fell, and the feed cuts out." },
  { v: "2.86.0", note: "A sonar ping now enrages everything that hears it — they sprint to the spot, then calm down." },
  { v: "2.85.0", note: "This update log, in Settings — page left/right through every version back to the first build." },
  { v: "2.84.0", note: "Broken windows now look like a clean hole cut in the wall, not tiled panels." },
  { v: "2.83.0", note: "Each wall shows a single dark line at its corners; the bloody wall writing is gone." },
  { v: "2.82.0", note: "Plain white-yellow floor and ceiling. Arrow keys ←/→ now turn the camera (A/D still strafe)." },
  { v: "2.81.0", note: "Walls repainted a flat, pale white-yellow." },
  { v: "2.80.0", note: "Security cameras: one occasionally hangs in a corner and turns to watch you." },
  { v: "2.79.0", note: "The death sequence is now a CCTV feed. A sonar ping is always heard by something." },
  { v: "2.78.0", note: "Death cutscene: after you're taken, something comes for the spot where you fell." },
  { v: "2.77.0", note: "Cleaner, flatter menu; a big “Join Random Seed” button; emojis removed." },
  { v: "2.76.0", note: "Room task clock tightened to 12 seconds, and you must open the locker by hand." },
  { v: "2.75.0", note: "The danger meter stays visible while you're at a keypad or terminal." },
  { v: "2.74.0", note: "Entities walk around broken windows instead of grinding into them." },
  { v: "2.73.0", note: "Safe-room tasks are timed — fail one and the door is breached, and a manhunt begins." },
  { v: "2.72.0", note: "Assembling a crucifix needs you to stand still, and stops energy regen while you work." },
  { v: "2.71.0", note: "No free sonar ping when you unpause. Safe rooms never go pitch black." },
  { v: "2.70.0", note: "The page quietly refreshes between games so you always get the newest build." },
  { v: "2.68.0", note: "A hunter won't give up while it can still see you." },
  { v: "2.67.0", note: "The corridor chase: keep running in a straight line and it keeps its eyes on you." },
  { v: "2.65.0", note: "The one rule that matters — look away — sits at the top of the rulebook." },
  { v: "2.64.0", note: "Standing still recovers energy fastest. Crucifix halves are assembled by hand." },
  { v: "2.63.0", note: "Crucifix halves — carry a top and a bottom and stop to fit them together." },
  { v: "2.62.0", note: "Loot lies where it fell, and the meat is a proper carcass." },
  { v: "2.61.0", note: "Loot rolls in two stages: about 5% of cells hold something, mostly meat." },
  { v: "2.60.0", note: "Real recorded audio for footsteps, movement and the sonar." },
  { v: "2.59.0", note: "Sonar costs a share of your energy. Real exhaustion, and the dark closes in when you're spent." },
  { v: "2.58.0", note: "Loot can scatter anywhere in a cell, not just the middle." },
  { v: "2.56.0", note: "A full in-game rulebook (How to Play)." },
  { v: "2.55.0", note: "The staring contest: hold eye contact too long and it fixates on you." },
  { v: "2.54.0", note: "Mutual gaze — look at one that's looking back and it has you, at any distance." },
  { v: "2.53.0", note: "Sonar cooldown of 17.5s — a real gap of darkness between pings." },
  { v: "2.52.0", note: "The danger meter became a signal-strength graph." },
  { v: "2.51.0", note: "The SEND SONAR button is itself the cooldown dial — it visibly recharges." },
  { v: "2.50.0", note: "Opaque menu panel, the danger bar, and the planks removed." },
  { v: "2.49.0", note: "The door code keypad moved onto the door itself." },
  { v: "2.48.0", note: "A ping costs 15% of your bar; its cooldown equals the glow time." },
  { v: "2.47.0", note: "10-second sonar cooldown." },
  { v: "2.46.0", note: "The radar maps everything in range; pings cost more." },
  { v: "2.45.0", note: "The ping now costs you energy." },
  { v: "2.44.0", note: "The door keypad remembers a half-entered code." },
  { v: "2.28.0", note: "The Safe Room Siege, settled onto the 2.x version line." },
  { v: "2.27.0", note: "Hunts always end: the crucifix wipes their memory, and they give up on their own." },
  { v: "2.26.0", note: "Sparser inhabitants, a yellow reveal, always-on radar dots, and glowing eyes." },
  { v: "2.25.0", note: "Chunk-placed loot and broken windows; they never appear in your view." },
  { v: "2.24.0", note: "Torches are one-time consumables — no more batteries." },
  { v: "2.23.0", note: "Two-stage awareness: sound makes them investigate, only sight makes them hunt." },
  { v: "2.22.0", note: "Full offline support, and scores sync once you're back online." },
  { v: "2.21.0", note: "The entities are inhabitants of the maze, already there — not spawned at you." },
  { v: "2.20.0", note: "The crucifix became a real panic button; spawns more spread out, more loot." },
  { v: "2.19.0", note: "Torch and batteries, and the drifting distance counter fixed." },
  { v: "2.18.0", note: "Three-second exposure after a ping; the crucifix as defence; quieter static." },
  { v: "2.17.0", note: "Carved liminal corridors, bigger chunks, and walking recovers energy." },
  { v: "2.16.0", note: "A silent sonar and an unsettling ambient room tone." },
  { v: "2.15.0", note: "No dead ends, cleaner footsteps, a realistic heartbeat, louder audio." },
  { v: "2.14.0", note: "A headphones prompt, and Settings folded into a collapsible tab." },
  { v: "2.13.0", note: "3D spatial entity audio with walls muffling it; energy and chase balance." },
  { v: "2.12.0", note: "A Minecraft-style hotbar inventory." },
  { v: "2.11.0", note: "Live threat dots, a safe start, a backpack, and a labelled run button." },
  { v: "2.10.0", note: "Entities hunt by line of sight and path around walls." },
  { v: "2.9.0", note: "Uniform difficulty, per-wall grime, mobile controls, line-of-sight radar." },
  { v: "2.8.0", note: "A proximity heartbeat, a fading radar minimap, and camera head-bob." },
  { v: "2.7.0", note: "Energy, running, stealth entities, the jumpscare, and meat pickups." },
  { v: "2.6.0", note: "Wavefront sonar, glow-in-the-dark reveal, and footsteps." },
  { v: "2.5.0", note: "Rare bloody writing on the walls, and a home-screen menu." },
  { v: "2.4.0", note: "Killer entities, a death state, flickering lights, and creepy walls." },
  { v: "2.3.0", note: "Username and password accounts (no email needed)." },
  { v: "2.2.0", note: "Accounts and a daily distance leaderboard." },
  { v: "2.1.0", note: "Minecraft-style seeds, the daily challenge, and adjustable look sensitivity." },
  { v: "2.0.0", note: "The pivot: E.C.H.0 becomes a 3D first-person Backrooms horror." },
  { v: "1.0.0", note: "The very first build." },
];
